# Generated by Django 2.0.13 on 2019-09-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20190818_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Law',
        ),
    ]
